theme = "mapstruct"
languageCode = "en-us"
baseurl = "http://mapstruct.org/"
title = "MapStruct"
paginate = 5
pluralizeListTitles = false
canonifyURLs = false
disqusShortname = "mapstruct"
googleAnalytics = "UA-41136939-1"
disablePathToLower = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
name = "News"
weight = 100
url = "/news/"

[[menu.main]]
name = "Documentation"
weight = 200

[[menu.main]]
name = "Community"
weight = 300

[[menu.main]]
name = "Development"
weight = 400


[[menu.main]]
name = "Examples"
post = "<i class='fa fa-external-link'></i>"
weight = 900
parent = "Documentation"
identifier = "examples"
url = "https://github.com/mapstruct/mapstruct-examples"

[[menu.main]]
name = "Code & Issues"
pre = "<i class='fa fa-github fa-lg'></i>"
weight = 900
identifier = "code-issues"
url = "https://github.com/mapstruct/mapstruct"

[Params]
stableVersion = "1.4.2.Final"
devVersion = "1.5.0.Beta2"
numberOfLatestPosts = 7
tagLine = "Java bean mappings, the easy way!"
contentSourceUrl = "https://github.com/mapstruct/mapstruct.org/tree/master/content/"
